build:
  image: epitechcontent/epitest-docker
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  script:
    - make re
  artifacts:
    paths:
      - myftp
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
# test:
#  stage: test
#  script:
#    - ./test_ftp.sh

deploy:
  image: epitechcontent/epitest-docker
  stage: deploy
  script:
    - echo "Pushing to $TARGET_REPO"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/epitech
    - chmod 600 ~/.ssh/epitech
    - git config core.sshCommand "ssh -o \"StrictHostKeyChecking=no\" -i ~/.ssh/epitech -F /dev/null"
    - git remote remove epitech || true
    - git remote add epitech $TARGET_REPO || true
    - git push --force-with-lease epitech $CI_COMMIT_REF_NAME
    - rm -rf ~/.ssh/epitech
